# -*- coding: utf-8 -*-
"""gradiente_descendiente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BS4EcXuN7m0MlU6hFdyt3iVAlHrRyE3I
"""

import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def grad_des (sym_func, sym_var, x_init, eta, eps, max_iter):
  # Calcular el gradiente de la función simbolica
  grad_sym = sp.Matrix([sym_func]).jacobian(sym_var)
  # Transforma de sym a numpy
  grad_num = sp.lambdify(sym_var, grad_sym, 'numpy')
  # Array de condiciones iniciales
  x = np.array(x_init)
  # Iteración de gradiente
  for i in range(max_iter):
    # Evalua el gradiente en x[k-1]
    # Se debe aplanar por la forma como se calcula grad_num
    grad = grad_num(*x).flatten()
    # Calcular x[k]
    x_new = x - eta * grad
    # Evaluar críterio de parada
    if (np.linalg.norm(grad) < eps):
      break
    x = x_new
  return x

# Variables simbolicas
x1, x2 = sp.symbols('x1 x2')

# Matrices
Q = sp.Matrix([[3, 1],
               [1, 2]])
b = sp.Matrix([2, 1])

#Vector de estados
x_vec = sp.Matrix([x1, x2])

# Función
f = (1/2)*(x_vec.T * Q * x_vec)[0] - (b.T * x_vec)[0]

ans = grad_des(f,[x1, x2],[0, 0],0.1,0.001,100)

print("Resultado:", ans)

f_eval =sp.lambdify(x_vec, f, 'numpy')

# Construir meshgrid para x_1 y x_2
x1_val = np.linspace(-2, 2, 100)
x2_val = np.linspace(-2, 2, 100)
X1, X2 = np.meshgrid(x1_val, x2_val)

# Obtener la superficie generada por f
Z = f_eval(X1, X2)

# Evaluar punto crítico para gráficar
z_p = f_eval(ans[0], ans[1])
min_grad = [ans[0], ans[1], z_p]

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(X1, X2, Z,alpha=0.8)
ax.scatter(ans[0], ans[1], z_p, color='red', marker='*')
ax.set_xlabel('x1')
ax.set_ylabel('x2')
ax.set_zlabel('f(x1,x2)')

plt.show()