# -*- coding: utf-8 -*-
"""TSP_NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnOcc9gjM-SarpeN9ma78dnfIUixImnR
"""

import math
import random
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.ticker import MultipleLocator

SEED      = 101        # Semilla random gen
N_CITIES  = 10        # Num ciudades
PLANE_MIN = 0         # Lim inf
PLANE_MAX = 20        # Lim sup

def generar_ciudades(n: int, low: float, high: float, seed: int) -> list[tuple]:
    random.seed(seed)
    ciudades = []
    for _ in range(n):
        ciudad = [round(random.uniform(low, high), 2),round(random.uniform(low, high), 2)]
        ciudades.append(ciudad)
    return ciudades

def distancia(p1: tuple, p2: tuple) -> float:
    return math.hypot(p2[0] - p1[0], p2[1] - p1[1])

def distancia_total(ruta: list, ciudades: list) -> float:
    total = 0.0
    n = len(ruta)
    for i in range(n):
        total += distancia(ciudades[ruta[i]], ciudades[ruta[(i + 1) % n]])
    return total

def vecino_mas_cercano(ciudades: list, inicio: int = 0) -> list:
    n = len(ciudades)
    visitado = [False] * n
    ruta = [inicio]
    visitado[inicio] = True

    for _ in range(n - 1):
        actual = ruta[-1]
        mejor_ciudad = None
        mejor_dist   = math.inf
        for j in range(n):
            if not visitado[j]:
                d = distancia(ciudades[actual], ciudades[j])
                if d < mejor_dist:
                    mejor_dist   = d
                    mejor_ciudad = j

        ruta.append(mejor_ciudad)
        visitado[mejor_ciudad] = True

    return ruta


def mejor_nn(ciudades: list) -> tuple[list, float]:
    mejor_ruta = None
    mejor_dist = math.inf

    for inicio in range(len(ciudades)):
        ruta = vecino_mas_cercano(ciudades, inicio)
        d    = distancia_total(ruta, ciudades)
        if d < mejor_dist:
            mejor_dist = d
            mejor_ruta = ruta

    return mejor_ruta, mejor_dist

def visualizar(ciudades, ruta_nn, dist_nn):
    etiquetas = list("ABCDEFGHIJ")[:len(ciudades)]

    fig, axes = plt.subplots(2, 1, figsize=(8, 15))

    rutas   = [None,ruta_nn,]
    titulos = ["Ciudades", f"Algoritmo Nearest Neighbor: {dist_nn:.2f}"]
    colores = ["blue","green"]

    for ax, titulo, ruta, color in zip(axes, titulos, rutas, colores):
        if ruta:
            for i in range(len(ruta)):
                a = ruta[i]
                b = ruta[(i + 1) % len(ruta)]
                x1, y1 = ciudades[a]
                x2, y2 = ciudades[b]
                ax.plot([x1, x2], [y1, y2], color=color, linewidth=1.5)
        xs = [c[0] for c in ciudades]
        ys = [c[1] for c in ciudades]
        ax.scatter(xs, ys, color="red", s=60, zorder=5)
        for i, (x, y) in enumerate(ciudades):
            ax.text(x, y + 0.5, etiquetas[i], ha="center", fontsize=9)
        ax.set_title(titulo)
        ax.set_xlim(-1, 21)
        ax.set_ylim(-1, 21)
        ax.grid(True, linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.show()

def main():
    ciudades = generar_ciudades(N_CITIES, PLANE_MIN, PLANE_MAX, SEED)
    print("\n|  ID  | Etiqueta |  Coordenadas    |")
    etiquetas = list("ABCDEFGHIJ")
    for i, (x, y) in enumerate(ciudades):
        print(f"|   {i}  |     {etiquetas[i]}    |  ({x:5.2f}, {y:5.2f}) |")

    ruta_nn, dist_nn = mejor_nn(ciudades)

    nombres_nn = [etiquetas[i] for i in ruta_nn] + [etiquetas[ruta_nn[0]]]
    print(f"Ruta Nearest Neighbor: {'>'.join(nombres_nn)}")
    print(f"Distancia ruta : {dist_nn:.4f}")
    visualizar(ciudades, ruta_nn, dist_nn)

if __name__ == "__main__":
    main()